import { randomBytes } from "node:crypto";
import type {
  ContainerNames,
  GameTemplate,
  GeneratedSecrets,
  InstanceContext,
  PortMap,
  VolumeSpec,
} from "./types.js";

// One contiguous block of 4 UDP ports per instance (game/query/battleye/von),
// matching arma_server/podman-compose.yml's "2302:2302/udp".."2305:2305/udp".
// The base is deliberately offset from arma_server's own single-instance
// default (2302) so the *first* hub-managed instance doesn't collide with a
// manually-run copy of that stack on the same host; allocation also does a
// live host-port check (see domain/instanceManager.ts) as a second layer of
// protection against any other listener, hub-managed or not.
// rcon_port is never published to the host (BattlEye RCon is reached from
// 127.0.0.1 *inside* the container only), so it can stay identical across
// every instance without colliding.
const GAME_PORT_BASE = 12302;
const GAME_PORT_STEP = 10;
const RCON_PORT = 2301;

export const arma3Template: GameTemplate = {
  gameType: "arma3",
  displayName: "Arma 3",
  repoDirName: "arma_server",
  images: {
    api: "localhost/arma3-manager-api:latest",
    frontend: "localhost/arma3-manager-frontend:latest",
  },
  defaultMemoryMb: 8192,

  allocatePorts(index: number, webPort: number): PortMap {
    const base = GAME_PORT_BASE + index * GAME_PORT_STEP;
    return {
      web: webPort,
      port: base,
      queryPort: base + 1,
      battleyePort: base + 2,
      vonPort: base + 3,
      rconPort: RCON_PORT,
    };
  },

  containerNames(slug: string): ContainerNames {
    return { api: `arma3-api-${slug}`, frontend: `arma3-frontend-${slug}` };
  },

  // Verified against arma_server's actual deploy.py (matches its
  // podman-compose.yml exactly for this game, unlike PZ's — see pz.ts).
  standaloneContainerNames: { api: "arma3-api", frontend: "arma3-frontend" },
  standaloneVolumeNames: ["arma3-server", "steam-home", "steam-config", "aspnet-keys"],

  networkName(slug: string): string {
    return `arma3-net-${slug}`;
  },

  volumes(slug: string): VolumeSpec[] {
    return [
      { name: `arma3-server-${slug}`, sizeable: true },
      { name: `steam-home-${slug}`, sizeable: false },
      { name: `steam-config-${slug}`, sizeable: false },
      { name: `aspnet-keys-${slug}`, sizeable: false },
    ];
  },

  portsToCheck(ports: PortMap) {
    return [
      { port: ports.web, protocol: "tcp" as const },
      { port: ports.port, protocol: "udp" as const },
      { port: ports.queryPort, protocol: "udp" as const },
      { port: ports.battleyePort, protocol: "udp" as const },
      { port: ports.vonPort, protocol: "udp" as const },
    ];
  },

  renderConfigToml(ctx: InstanceContext, ports: PortMap): string {
    return `# Generated by Server Hub for instance "${ctx.name}" (${ctx.id}). Do not edit ports here
# without updating the hub's instance record — they must match the podman run
# port mappings created alongside this file.

[web]
port = 8080
public_port = ${ports.web}
bind_ip = "0.0.0.0"
username = "admin"
base_url = ""
frontend_origin = ""
public_join_host = ""

[server]
arma3_dir = "/arma3"
steamcmd_dir = "/steamcmd"
port = ${ports.port}
query_port = ${ports.queryPort}
battleye_port = ${ports.battleyePort}
von_port = ${ports.vonPort}
rcon_port = ${ports.rconPort}
max_players = 40
memory_limit = "${ctx.memoryMb}m"
network_mode = "bridge"

[steam]
user = "anonymous"
owner_ids = []
creator_dlc_app_ids = []

[runtime]
timezone = "UTC"
mock_server = ${ctx.mock}
mock_steamcmd = ${ctx.mock}

[history]
retention_days = 90
`;
  },

  generateSecrets(): GeneratedSecrets {
    const initialPassword = randomBytes(18).toString("base64url");
    const sessionSecret = randomBytes(32).toString("hex");
    const rconPassword = randomBytes(24).toString("base64url");
    const content = `# Generated by Server Hub. Keep this file private.

[web]
password = "${initialPassword}"
session_secret = "${sessionSecret}"

[server]
rcon_password = "${rconPassword}"

[steam]
password = ""
`;
    return { content, initialPassword };
  },

  apiRunArgs(ctx: InstanceContext, ports: PortMap): string[] {
    const names = this.containerNames(ctx.slug);
    const [serverVol, steamHomeVol, steamConfigVol, aspnetVol] = this.volumes(ctx.slug).map((v) => v.name);
    return [
      "--name",
      names.api,
      "--restart",
      "unless-stopped",
      "--memory",
      `${ctx.memoryMb}m`,
      "--network",
      this.networkName(ctx.slug),
      "-p",
      `${ports.port}:${ports.port}/udp`,
      "-p",
      `${ports.queryPort}:${ports.queryPort}/udp`,
      "-p",
      `${ports.battleyePort}:${ports.battleyePort}/udp`,
      "-p",
      `${ports.vonPort}:${ports.vonPort}/udp`,
      "-v",
      `${ctx.configDir}:/app/config:ro`,
      "-v",
      "/sys:/host-sys:ro",
      "-v",
      `${serverVol}:/arma3`,
      "-v",
      `${steamHomeVol}:/home/arma3/Steam`,
      "-v",
      `${steamConfigVol}:/home/arma3/.steam`,
      "-v",
      `${aspnetVol}:/home/arma3/.aspnet`,
    ];
  },

  frontendRunArgs(ctx: InstanceContext, ports: PortMap): string[] {
    const names = this.containerNames(ctx.slug);
    return [
      "--name",
      names.frontend,
      "--restart",
      "unless-stopped",
      "--network",
      this.networkName(ctx.slug),
      "-p",
      `127.0.0.1:${ports.web}:8080/tcp`,
      "-e",
      "ARMA3_API_BASE=",
      "-e",
      "ARMA3_REST_ONLY=true",
      "-e",
      `ARMA3_API_BACKEND=${names.api}:8080`,
    ];
  },

  panelUrl(ports: PortMap): string {
    return `http://127.0.0.1:${ports.web}`;
  },
};
