import { randomBytes } from "node:crypto";
import type {
  ContainerNames,
  GameTemplate,
  GeneratedSecrets,
  InstanceContext,
  PortMap,
  VolumeSpec,
} from "./types.js";
import { escapeTomlString } from "./tomlUtil.js";

// game_port publishes a wide range (gamePort..gamePort+100) to cover the
// dynamic player-port span, matching proyect_zomboid/podman-compose.yml's
// "16261-16361:16261-16361/udp". rcon_port is a single TCP port. The Steam
// query ports (8766/8767 UDP) are hardcoded inside the PZ server binary
// itself (not configurable via manager.toml or any startup flag in
// proyect_zomboid's backend) — the hub still gives each PZ instance its own
// distinct *host*-side port for them via bridge-network remapping, so
// multiple instances can run at once without a port conflict.
//
// All bases are deliberately offset from proyect_zomboid's own
// single-instance defaults (16261/27015/8766) so the *first* hub-managed
// instance doesn't collide with a manually-run copy of that stack on the
// same host; allocation also does a live host-port check (see
// domain/instanceManager.ts) as a second layer of protection.
const GAME_PORT_BASE = 26261;
const GAME_PORT_STEP = 150;
const GAME_PORT_RANGE_WIDTH = 100;
const RCON_PORT_BASE = 37015;
const STEAM_QUERY_PORT_BASE = 18766;
const STEAM_QUERY_PORT_STEP = 2;
// Container --memory headroom above the JVM heap (memory_limit_mb feeds
// -Xmx), matching the ~+2GB gap between proyect_zomboid's own
// manager.toml default (4096) and its podman-compose.yml mem_limit (6g).
const CONTAINER_MEMORY_HEADROOM_MB = 2048;

export const pzTemplate: GameTemplate = {
  gameType: "pz",
  displayName: "Project Zomboid",
  repoDirName: "proyect_zomboid",
  images: {
    api: "localhost/pz-manager-api:latest",
    frontend: "localhost/pz-manager-frontend:latest",
  },
  defaultMemoryMb: 4096,

  allocatePorts(index: number, webPort: number): PortMap {
    return {
      web: webPort,
      gamePort: GAME_PORT_BASE + index * GAME_PORT_STEP,
      rconPort: RCON_PORT_BASE + index,
      steamQueryPort1: STEAM_QUERY_PORT_BASE + index * STEAM_QUERY_PORT_STEP,
      steamQueryPort2: STEAM_QUERY_PORT_BASE + index * STEAM_QUERY_PORT_STEP + 1,
    };
  },

  containerNames(slug: string): ContainerNames {
    return { api: `pz-api-${slug}`, frontend: `pz-frontend-${slug}` };
  },

  networkName(slug: string): string {
    return `pz-net-${slug}`;
  },

  volumes(slug: string): VolumeSpec[] {
    return [
      { name: `pz-install-${slug}`, sizeable: true },
      { name: `pz-data-${slug}`, sizeable: true },
      { name: `pz-steamcmd-${slug}`, sizeable: false },
      { name: `pz-backups-${slug}`, sizeable: true },
    ];
  },

  portsToCheck(ports: PortMap) {
    return [
      { port: ports.web, protocol: "tcp" as const },
      { port: ports.gamePort, protocol: "udp" as const },
      { port: ports.rconPort, protocol: "tcp" as const },
      { port: ports.steamQueryPort1, protocol: "udp" as const },
      { port: ports.steamQueryPort2, protocol: "udp" as const },
    ];
  },

  renderConfigToml(ctx: InstanceContext, ports: PortMap): string {
    return `# Generated by Server Hub for instance "${ctx.name}" (${ctx.id}). Do not edit ports here
# without updating the hub's instance record — they must match the podman run
# port mappings created alongside this file.

[web]
port = 8080
public_port = ${ports.web}
bind_ip = "0.0.0.0"
username = "admin"
base_url = ""

[server]
zomboid_install_dir = "/pz/install"
zomboid_data_dir = "/pz/data"
steamcmd_dir = "/pz/steamcmd"
server_name = "${escapeTomlString(ctx.name)}"
public_address = ""
game_port = ${ports.gamePort}
rcon_port = ${ports.rconPort}
memory_limit_mb = ${ctx.memoryMb}
network_mode = "bridge"

[steam]
owner_ids = []

[runtime]
timezone = "UTC"
mock_steamcmd = ${ctx.mock}
mock_server_binary = ${ctx.mock}

[history]
retention_days = 30

[backups]
dir = "/pz/backups"
retain_scheduled_count = 10
retain_other_count = 5
schedule_interval_hours = 0
`;
  },

  generateSecrets(): GeneratedSecrets {
    const initialPassword = randomBytes(18).toString("base64url");
    const sessionSecret = randomBytes(32).toString("hex");
    const rconPassword = randomBytes(24).toString("base64url");
    const adminPassword = randomBytes(18).toString("base64url");
    const content = `# Generated by Server Hub. Keep this file private.

[web]
password = "${initialPassword}"
session_secret = "${sessionSecret}"

[server]
admin_password = "${adminPassword}"
rcon_password = "${rconPassword}"

[steam]
password = ""
`;
    return { content, initialPassword };
  },

  apiRunArgs(ctx: InstanceContext, ports: PortMap): string[] {
    const names = this.containerNames(ctx.slug);
    const [installVol, dataVol, steamcmdVol, backupsVol] = this.volumes(ctx.slug).map((v) => v.name);
    const rangeEnd = ports.gamePort + GAME_PORT_RANGE_WIDTH;
    return [
      "--name",
      names.api,
      "--restart",
      "unless-stopped",
      "--memory",
      `${ctx.memoryMb + CONTAINER_MEMORY_HEADROOM_MB}m`,
      "--network",
      this.networkName(ctx.slug),
      "-p",
      `${ports.gamePort}-${rangeEnd}:${ports.gamePort}-${rangeEnd}/udp`,
      "-p",
      `${ports.rconPort}:${ports.rconPort}/tcp`,
      "-p",
      `${ports.steamQueryPort1}:8766/udp`,
      "-p",
      `${ports.steamQueryPort2}:8767/udp`,
      "-v",
      `${ctx.configDir}:/app/config:ro`,
      "-v",
      `${installVol}:/pz/install`,
      "-v",
      `${dataVol}:/pz/data`,
      "-v",
      `${steamcmdVol}:/pz/steamcmd`,
      "-v",
      `${backupsVol}:/pz/backups`,
    ];
  },

  frontendRunArgs(ctx: InstanceContext, ports: PortMap): string[] {
    const names = this.containerNames(ctx.slug);
    return [
      "--name",
      names.frontend,
      "--restart",
      "unless-stopped",
      "--network",
      this.networkName(ctx.slug),
      "-p",
      `127.0.0.1:${ports.web}:80/tcp`,
      "-e",
      `PZ_MANAGER_API_BACKEND=${names.api}:8080`,
    ];
  },

  panelUrl(ports: PortMap): string {
    return `http://127.0.0.1:${ports.web}`;
  },
};
